#!/bin/bash
BKPDir="/Users/Niels/BKP_TEST_IOSFARM"
##cosmetic functions and Variables

##Colors
RED='\033[0;31m'
YELLOW='\033[0;33m'
GREEN='\033[0;32m'
NC='\033[0m'
BLUE='\033[0;34m'

##Break function for readabillity
function BR {
  echo "  "
}

##DoubleBreak function for readabillity
function DBR {
  echo " "
  echo " "
}

##paths:
#fixDate=$(date)
fixDate=$(date +"%Y%m%d - %Hh%M")
echo fixDate: $fixDate
scriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
originalBlobSave="$scriptDir/BlobSave"
echo originalBlobSave: $originalBlobSave
originalLists="$scriptDir/Lists"
echo originalLists: $originalLists


echo BKPDir: $BKPDir
dateDir="$BKPDir/$fixDate"
echo dateDir: $dateDir
##---------------------------------------------------------------------------

##DateDir
function DateDir {
  if [[ -d "$dateDir" ]]
  then
    printf "${GREEN}Date directory is available${NC}\n"
    BR
  else
    printf "${RED}Date directory is not available,${GREEN} creating the directory${NC}\n"
    BR
    mkdir "$dateDir"
  fi
}

##Copy
function copy {
  cp -v -p -R "$originalBlobSave" "$dateDir"
  cp -v -p -R "$originalLists" "$dateDir"
}

##backupDir
if [[ ! -d "$BKPDir" ]]
 then
  printf "${RED}backupDir is not available, please check the path in the beginning of te script and restart the script${NC}\n"
  BR
  exit -1
else
  DateDir
  copy
fi
