#!/bin/bash
##paths

##Script directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
##path for the iosList
iosFile="$DIR/Lists/iosList.csv"
##path for the DeviceList
deviceFile="$DIR/Lists/DeviceList.csv"
##path for the bloblist
bloblist="$DIR/Lists/BlobList.csv"
##path to TSSCHECKER_OLD
# tssPath="$DIR/tsschecker_macos"
##path to TSSCHECKER_NEW
tssPath="$DIR/tsschecker"
#setting the delimiter
IFS=";"
#Fix the date Variable
DATE=$(date)



##predeclare
iosVersionArray=()

##cosmetic functions and Variables
##Colors
RED='\033[0;31m'
YELLOW='\033[0;33m'
GREEN='\033[0;32m'
NC='\033[0m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'

##Break function for readabillity
function BR {
  echo "  "
}

##DoubleBreak function for readabillity
function DBR {
  echo " "
  echo " "
}

##The actual Code
##---------------

#function to grab the wanted ios versions
function ios {
  while read ios
  do
    iosVersionArray+=("$ios")
  done < $iosFile
  ##for testing:
  printf "${YELLOW}Downloading blobs for these ios versions:${NC}\n"
  for index  in ${!iosVersionArray[*]}
  do
    echo ${iosVersionArray[$index]}
  done
}


function blob {
  ##Getting the arraylenght from the devicelist
  deviceArrayLength=$(grep -o  'iP' $deviceFile | wc -l)
  ##Getting the arraylenght form the iosversions
  IOSArrayLength=${#iosVersionArray[@]}
  ##Setting the loop counters
  deviceCounter=0
  iosCounter=0

  while [[ $iosVersionArray ]]
  iosVersion=${iosVersionArray[$iosCounter]}
  BR
  do
    while read ECID UDID serial devicetype devicemodel
    do
      ##echos for debugging
      printf "${RED}DEBUGGING:${NC}\n"
      printf "ECID: ${MAGENTA}$ECID${NC}\n"
      printf "UDID: ${MAGENTA}$UDID${NC}\n"
      printf "Serial: ${MAGENTA}$serial${NC}\n"
      printf "devicetype: ${MAGENTA}$devicetype${NC}\n"
      printf "devicemodel: ${MAGENTA}$devicemodel${NC}\n"
      ##check for BlobSave directory
      if [[ -d "$DIR/BlobSave" ]]
      then
        printf "${GREEN}BlobSave directory is available${NC}\n"
        BR
      else
        printf "${RED}BlobSave directory is not available,${GREEN} creating the directory${NC}\n"
        BR
        mkdir $DIR/BlobSave
      fi

      ##check for save directory
      if [ -d "$DIR/BlobSave/$serial/$iosVersion" ]
      then
        printf "${GREEN}Storage directory available, proceeding downloading the blob${NC}\n"
      else
        printf "${RED}directory not available, ${GREEN}creating the needed storage directories${NC}\n"
        BR
        cd $DIR/BlobSave
        mkdir $serial
        mkdir $serial/$iosVersion
        printf "${YELLOW}$dir "/BlobSave/"$serial/$iosVersion "created"${NC}\n"
        BR
      fi

      ## getting the blob
      #BlobSavePath
      BlobSavePath="$DIR/BlobSave/$serial/$iosVersion"
      #$tssPath -d $devicetype -e $ECID -i $iosVersion --boardconfig "$devicemodel" -s --save-path $BlobSavePath
      $tssPath -d "$devicetype" -i "$iosVersion" --boardconfig "$devicemodel" -e "$ECID" -s --save-path "$BlobSavePath"
      pathforCSV=$(ls -rt  $BlobSavePath  | tail -n 1)
      echo "$serial;$ECID;$iosVersion;$(date);$pathforCSV;$BlobSavePath/$pathforCSV" >> $bloblist
      printf "${YELLOW}Blob saved to: $BlobSavePath ${NC}\n"
      BR

    done < $deviceFile

    ((iosCounter++))

    if [[ $iosCounter -eq $IOSArrayLength ]]
    then
      printf "${GREEN}All available blobs are saved!"
      exit
    fi
  done
}
ios
blob
